from fast_fuzzymatch import (
    preprocess,
    preprocessList,
    fast_fuzzymatchBatch,
    fast_fuzzymatch
)

print(fuzzymatch(b'test', b'staphylococci'))
print(fast_fuzzymatch(b'test', b'staphylococcies'))

# import time


# wordset = [
#     'triad', 'section', 'trochanger', 'stapylococcus',
#     'tendineae', 'stratal', 'thumb', 'tmpym2zul', 'tmpkchdsn', 'state',
#     'sulfotransferase', 'tmpgqbsu', 'staphylococci', 'tests', 'styloid',
#     'subtalar', 'tinib', 'essential', 'sw0darqft7', 'society', 'tunica',
#     'transmembrane', 'tyrosinase', 'intersphincteric', 'transforming',
#     'trachea', 'thickened', 'tmppxk4fn', 'telomerase', 'sagittal', 'storm',
#     'santorini', 'esterification', 'gastrojejunostomy', 'thymus', 'sternum',
#     'streaks', 'tremens', 'semantics', 'tmpa45mfz', 'saturated', 'sciatic',
#     'tracking', 'counterpulsation', 'thoraco', 'shift', 'sacrotuberous',
#     'intestines', 'tmpimdiif', 'symptoms', 'segmented', 'tmpmc56ih',
#     'stretching', 'supraoptic', 'tmpocm10o', 'tamulosin', 'tmpjanqzj',
#     'stage3', 'tenderness', 'elispot', 'transcranial', 'trypsin',
#     'tmpipxvnz', 'tmpsaldpu', 'tmp0ljhyb', 'tacrine', 'septic', 'tmpbqhy3x',
#     'stupor', 't7zklrq7', 'storage', 'sphincteric', 'snatching',
#     'tmpyqnpbp', 'thalamic', 'tmpof', 'stenosis', 'selective', 'suction',
#     'frotteuristic', 'talocalcaneal', 'superparamagnetic', 'sublimation',
#     'trachiaesophageal', 'subject', 'therapy', 'signet', 'streptococcal',
#     'anticholinesterase', 'stroke', 'taxonomic', 'study', 'tarsal',
#     'trichohyaline', 'tracheo', 'tempora', 'teres', 'subendothelial',
#     'tuberoinfundibular', 'tmpfzr9do', 'tmpc8l', 'teicoplanin', 'tuberal',
#     'intercostal', 'supination', 'southern', 'transcellular', 'static',
#     'northwest', 'tmpikoxr2', 'tmp3mgmpk', 'tmp13e71e', 'switchng',
#     'tmpzev74r', 'tmppgh5o1', 'stabilize', 'gastrointestinal',
#     'uncharacteristic', 'tmpibcvur', 'tmplf45w8', 'thelazia', 'trapezius',
#     'taeniae', 'tbu1nomuo2ysgbgfmmk1', 'tmpf22w', 'spectoscopy',
#     'tmpaflph7', 'thalassemia', 'termi', 'tmpo7cdj8', 'sporocyte',
#     'sucralfate', 'streak', 'tmpos7', 'characteristic', 'skrtwnfha',
#     'times', 'atherosclerotic', 'taxol', 'still', 'stratified',
#     'thyroglobulin', 'tmp00hneb', 'tqnh81r3', 'tmprio7ka', 'tmplvew3w',
#     'tahorbzhnb1ewbv', 'trabecular', 'tyramine', 'spirochaetaceae',
#     'terminal', 'tmpnecue0', 'salient', 'stream', 'stapedius',
#     'suboccipitial', 'tmpmhwpfj', 'stripe', 't0zd5u8', 'sterile', 'tarceva',
#     'thrombus', 'stamp', 'tmpi8bso5', 'stretch', 'topographic',
#     'tppsxuo3swzhpzycjmpgu', 'silhouette', 'specificity', 'tmpjfwhwg',
#     'segmentectomy', 'thalmic', 'segmentation', 'encysted', 'tomographic',
#     'spirochaetes', 'tolerance', 'tubular', 'tumu39qnpvxau87bffcd1',
#     'tmpe4lagk', 'tmp4kvfi2', 'tmpn4yf5e', 'trans', 'staphyococcul',
#     'tspbfefqholcxqaqb', 'thyoid', 'thena', 'erythroblastic',
#     'slqdwcmb3ppvceutbv49o', 'transvestism', 'satorius', 'thyroidism',
#     'superantigen', 'typical', 'tibiocalcaneal', 'tendon', 'taurine',
#     'steady', 'symaptic', 'stand', 'tmp0ex2k4', 'trophic', 'tmpefxaof',
#     'sweating', 'triscupid', 'tmpafygf', 'thrush', 'etastasis', 'tmpc2bkz7',
#     'symmetric', 'tingle', 'tmpsyw3oy', 'gastroduodenostomy',
#     'striation', 'tracheomalacia', 'tmpnue8bk', 'tmpwncvql', 'stereotype',
#     'traveler', 'serotype', 'spect', 'tmp9zl3u8', 'sheet', 'stack',
#     'estulic', 'tripolar', 'striae', 'tmplxucga', 'schitosome', 'steatosis',
#     'tmprqxhs5', 'spinothalmic', 'tubulovillous', 'tryparsamide',
#     'tmpz9sbal', 'steep', 'transgenic', 'tmppwkpak', 'synchronization',
#     'tmppcnqhj', 'tmpnphxjv', 'synthesis', 'tmp8fexxd', 'tranylcypromine',
#     'sinoatrial', 'symporter', 'intestinal', 'sclerotherapy', 'tmpg3j7cq',
#     'tsdg65quddo2ogj7i7qlm', 'tmpesgodn', 'secreting', 'trichome',
#     'starvation', 'steven', 'somatomedin', 'evisceration', 'tmphzizy6',
#     'tmpauf2g0', 'tmpdccgd7', 'trichomonas', 'sphincterectomy', 'stone',
#     'tmpvr5nnr', 'tmp1n5jdv', 'serratus', 'bacteroistatic', 'segmental',
#     'tracer', 'tmprjr4eo', 'trypanosoma', 'thrombin', 'suboccipital',
#     'tmpwqjjol', 'osteoclast', 'trigeminary', 'turning', 'simulation',
#     'sporozoite', 'strongyloides', 'sertraline', 'tmpl2l2sv', 'transfusion',
#     'tubercle', 'sulfation', 'elasticity', 'switched', 'stress',
#     'tmpxn01pj', 'tmpqnolhx', 'tmpm50ckb', 'through', 'tuberous',
#     'thalidomide', 'tmpdwfyfy', 'tachy', 'tmpeodbcz', 'scatchard',
#     'excystation', 'splitting', 'smooth', 'staging', 'tropin', 'scrotum',
#     'supraventricular', 'tmphfjucy', 'technology', 'tracheostomy',
#     'tmpysl7kl', 'extravasation', 'setpated', 'troponin', 'interest',
#     'solitarius', 'transvenous', 'tachycardia', 'tmplf8kgo', 'tmp9qessm',
#     'sporotrichosis', 'tmpxghnvv', 'tmpokzgzw', 'thromboxane', 'tmp4xaui3',
#     'tracks', 'tmpkv7gp5', 'scarlet', 'tmp1eo2ni', 'tmpmgby26', 'septum',
#     'stomach', 'thoracodorsal', 'interstitospinal', 'thoracoacromial',
#     'switch', 't9lh2foxvzaph', 'subintimal', 'thebesian', 'tmpbehgrl',
#     'trunc', 'strech', 'timing', 'tmp4fubhf', 'transpyloric', 'tcell',
#     'sternocleidomastoid', 'tmpoqfufe', 'thyro', 'tmp3nvyvf', 'interstitum',
#     'tmpnayv20', 'tmp55k7jo', 'stranger', 'tenodesis', 'torado',
#     'tmpilsqc6', 'tmpbaavkw', 'tmplssvn6', 'transferrin', 'sphincter',
#     'tempoary', 'talocrural', 'tmpvjdswj', 'svtn850vhvkth9ftizwp',
#     's0iitge7o1i5r', 'surfactant', 'sterol', 'staa5', 'toxicosis', 'talus',
#     'cvt4eoqsg9wlv0vifp1et', 'tgmqas5vvnkmc', 'thorombosis', 'esterase',
#     'taxanes', 'spermatic', 'subthalamic', 'split', 'stasis', 'stigmine',
#     'tmpjpvxgs', 'tmp6p2vaj', 'turner', 'tmpi3r7vw', 'interpositus',
#     'saginata', 'tmparzu4k', 'tracebular', 'sheth', 'tissues', 'stereo',
#     'tidine', 'esters', 'touch', 'tmp3blfq2', 'third', 'tmpcyjbje',
#     'tandem', 'sq15lkxctnww3qqf', 'tmpayqnd2', 'truncus', 'tmpn77dou',
#     'encapsulated', 'tomography', 'tmaqlmzgwbzdjqhwfqj0v', 'tmpp6bjuy',
#     'twgcp3opcyji3zrduzrww', 'tmpo8phxx', 'tmp3cxlhq', 'trophy',
#     'tmpsc5dqq', 'segment', 'stapler', 'sedative', 'typhi', 'synthase',
#     'thrombolysis', 'satelite', 'stimulant', 'tv6nsnyyo', 'spontaneous',
#     'scatter', 'tmp5lype9', 'tmpwulby2', 'steatorrhea', 'strong', 'tibia',
#     'talocalcaneonavicular', 'smith', 'ticarcillin', 'thyroxine',
#     'thickness', 'stalts', 'staphylo', 'tmpin7ue9', 'salmeterol', 'tmpsi',
#     'splenectomy', 'tigar', 'tmpajfaph', 'standard', 'efdkq8xateasnlvhtiyw',
#     'tmpl2roun', 'acetylcholinesterase', 'trochlear', 'toxocara',
#     'sternothyroid', 'stomal', 'estrogen', 'se1zk3r0flwbxytzxs',
#     'intensity', 'tmpsgismf', 'trend', 'tenex', 'salivatory', 'thrombic',
#     'tcf7l2', 'ts6anpeygxqlz', 'striatum', 'tmppdjg5j', 'spironolactone',
#     'tmp7y35s9', 'theranostics', 'transform', 'tuberculosis', 'sprout',
#     'termialis', 'strauss', 'tmpdwos8s', 'toxigenic', 'semantic',
#     'trihexyphenidyl', 'stratium', 'esophagogastroduodenoscopy',
#     'stimulation', 'tmpnrou2u', 'tobramycin', 'sv7va9pj1tac', 'subtantia',
#     'tmpj8pche', 'scatta', 'tmpcs9brk', 'ureterostomy', 'tmpm9aeju',
#     'staphyococcal', 'tmppocvaj', 't3l41ce4bebfyuhazwcu', 'staphylococcal',
#     'testing', 'eustachio', 'toxins', 'trimer', 'strategy',
#     'encystation', 'striosome', 'sulfactant', 'extrasphincteric',
#     'temporal', 'tmpei', 'seperated', 'toddler', 'status', 'shunted',
#     'tmpumm3rm', 'solitariothalamic', 'sorbitol', 'tssxaplzkbjce0efia3vh',
#     'tunnel', 'tmpzsj4ip', 'tachypnea', 'shilouette', 'satelliting',
#     'tzbzsmzvawbf', 'sites', 'tumescent', 'tmpqqgg45', 'supraglottic',
#     'transversum', 'tpvpvm', 'tmpadqjwj', 'stria', 'tamoxifen',
#     'tamsulosin', 'tracheal', 'ithpns0cyinbesbvo9ftp', 'symptom',
#     'tonsilar', 'supratrochlear', 'eustress', 'stimulator', 'treadmill',
#     'tmpwub6mv', 'selectivity', 'spirochetes', 'spatiotemporal',
#     'tmpludg7e', 'tmpkmadlj', 'tmpymofcr', 'seton', 'tobacco', 'stoma',
#     'stimuli', 'secretion', 'trial', 'tmp5rvknr', 'typhoid', 'syncitium',
#     'solitary', 'tmpzslsyf', 's4ktdnxgsfgxpld2qvf29', 'tmpmalpdv',
#     'subjective', 'solubility', 'trapping', 'stapes', 'strike', 'tmpiwqy4m',
#     'trali', 'tmp9v5iau', 'three', 'scant', 'tracebula', 'stiffness',
#     'toxemic', 'tmpkaqvjs', 'tmpgwmgpj', 'typhus', 'tmp4uaxwq',
#     'scattering', 'statin', 'tmp3ww', 'synthetic', 'tmphc19pz', 'starling',
#     'tissue', 'tmp5zywsj', 'trade', 'ergosterol', 'intertestinal',
#     'trepanning', 'significant', 'spirit', 'tuberalis', 'tacoplanin',
#     'sartorius', 'shunting', 'tmpkduddo', 'tensor', 'tmpicdzfe', 'serrated',
#     'tmpok7wz6', 'tmpbohvhn', 'style', 't9byrhj4fkemsdwprljfx',
#     'supprative', 'tmpwjyxoc', 'tmpvwhvsn', 'tubocurarine', 'tmpuz',
#     'staphylococcus', 'trepopnea', 'spatial', 'seawater', 'tgucrxkme1m',
#     'tmp8zowcw', 'secretory', 'selectin', 'tyrosine', 'wintersteiner',
#     'tmprhmiqy', 'treponema', 'tmp53a3ux', 'streptococci', 'tmpypjsji',
#     'tmpxyx00j', 'tapsin', 'tyzw0u75snmcc1wygxsgz', 's4wfktl1srhwvh',
#     'somato', 'tzunwgdm', 'tidal', 'trazodone', 'syntax', 'tmpymuazg',
#     'tpg2rfiyrbc9kuq8n8rv', 'tmppury8i', 'salts', 'elasticus',
#     'transferase', 'tevar', 'tmpyklbnd', 'tibialis', 'technique',
#     'tmpzkihum', 'tmpebbxmh', 'standardized', 'solute', 'trichuris',
#     'tmph5pk0r', 'characteristics', 'somatosensory', 'transversalis',
#     'shuntwiki', 'tmprkbozu', 'tf1inurrs2pknvy8gz53e', 'artesunate',
#     'testicular', 'tmpax1wq1', 'tpkfkjjawlsuryvyfkcgb', 'tmpgqrhjw',
#     'tubes', 'steatofibrosis', 'tmpasvsoq', 'ewz1dsua57rzpvytlp5ma',
#     'tmphuh0fo', 'srbct', 'thenar', 'tmpozsaqm', 'triange', 'tmpp22wps',
#     'satiety', 'shunt', 'tfhpe48', 'tmplnw7xf', 'tmpwohzs3', 'scotopsin',
#     'tympanic', 'tmpejc965', 'tonic', 'ester', 'tuberculin', 'subunit',
#     'trapezium', 'tounge', 'tricuspid', 'thorax', 'toxinogenic',
#     'toxocarasis', 'sweat', 'tmplkh1s9', 'setting', 'tmpslkhz5',
#     'erasistratus', 'protest', 'terazosin', 'tmpuqwjrb', 'short',
#     'heterozygosity', 'stick', 'tibiofibular', 'sqatting', 'triazole',
#     'ticargrelor', 'thallium', 'streptococcus', 'erythroblastosis',
#     'thromboembolism', 'tyroglobulin', 'table', 'sulbactam', 'tmpybkqln',
#     'stellate', 'spirochaetae', 'tmprley1g', 'sputum', 'tmpzu8y8j',
#     'tmpqfj0gk', 'terbinafine', 'symprort', 'tmpsr', 'topical', 'tmpifnc61',
#     'streth', 'stroma', 'tmp4zhsl9', 'strut', 'td6suvpcjmpsd', 'tmpz9grlm',
#     'stereotactic', 'tmpypjoq6', 'triangluaris', 'tmpu1emp5', 'tmplygoo5',
#     'tmpqvp0rm', 'trimoxazole', 'tmpbq9', 'tmpf4mhvr', 'stereorype',
#     'tmpfzephj', 'station', 'trigone', 'segments', 'tmpvmxv8m',
#     'thiazolidinediones', 'somatotrope', 'stable', 'symptomatic',
#     'synarthrosis', 'tmp64rdsr', 'tuberculoid', 'tmpqya3qq', 'subacute',
#     'stage', 'structural', 'ntfbduxedrs6m1rttqd', 'stiff', 'tmp0bvqpy',
#     'thyrohyoid', 'thoracic', 'toxin', 'toxoplasma', 'terminalis', 'tropic',
#     'temporo', 'strand', 'shaft', 'tdu1ksm5d2lzfox', 'straited',
#     'interpositorubral', 'transversospinalis', 'stromal', 'tmpexqvc3',
#     'submental', 'topoisomerase', 'transference', 'elastography',
#     'trichrome', 'tmp505b3v', 'tmpwacbjf', 'tuia7fuoywynk9cqo', 'tmparjqzo',
#     'storiform', 'striated', 'stricture', 'tmphqp5ed', 'tmpbevd6o',
#     'thrombi', 'serotonin', 'turbulency', 'tubulointerstitial', 'topic',
#     'streptozotocin', 'tmpnbawcu', 'schizont', 'tmp2gpuox', 'tmpfylrfl',
#     'tranquilizer', 'photosensitivity', 'suppurative', 'triglyceride',
#     'situs', 'trichinella', 'tmpxiqkgn', 'treponemal', 'interstitiospinal',
#     'trabecula', 'tendency', 'tmpah0dh8', 'subjects', 'staturation',
#     'tmpzzzvbp', 'septick', 'tmp5mi1p7', 'sternal', 'stuporous',
#     'tubulovesicle', 'subepithelial', 'these', 'sk9hzyyuie4idzifeotey',
#     'thyroid', 'torsade', 'tmpkmo295', 'tmpagall7', 'tmpgqrs5f',
#     'strawberry', 'supraorbital', 's38t27jtfgmy5gfdtv4wv', 'secreton',
#     'elastic', 'tmpzudsmb', 'stty4nzti', 'trigger', 'tmpo3r1su',
#     'tigecycline', 'tolcapone', 'testes', 'transverse', 'trauma', 'spotted',
#     'sting', 'tmp6xyx3d', 'tonsil', 'tuberosiry', 'steroid', 'triple',
#     'staphyococcus', 'semitendinosus', 't00nd0solvhb5he60qcvk', 'theca',
#     'tmphcybdk', 'tezyu7vgzjp', 'telenzepine', 'tmpoyu8rh',
#     'eiv4jsfemtdmzp9zlh', 'stimulatory', 'transpulmonary',
#     't3kfbarqyrnlbhzyxg0sb', 'torsades', 'stressor', 'tmpfs35nz',
#     'tmpa8zfyo', 'tmps6djp7', 'tmpzpwadk', 'tmpwcbsak', 'tmpih7b2u',
#     'interposition', 'supplimental', 'seperation', 'spirometra',
#     'tmpbz0ihq', 'autodigestion', 'theophylline', 'tmps1o', 'sternocostal',
#     'terreus', 'tendinous', 'tingible', 'tmpxsuwx1', 'symbolization',
#     'septis', 'theory', 'tmpcleq7n', 'tkdd0rs', 'synaptic', 'interstitium',
#     'intestine', 'supportice', 'torsion', 'tacrolimus', 'stool',
#     'selection', 'epstein', 'hepatoprotoenterostomy', 'tbody', 'tremor',
#     'tskyedkm0xh9d', 'sxtfa', 'thoracoepigastric', 'triangular', 'tropical',
#     'singularity', 'sawtooth', 'transducer', 'sztl5xlkohur2kym507fl',
#     'tmpc8ylk5', 'tmp5fusdc', 'squatting', 'tmp6yeisk', 'tmpcmhrmn',
#     'sphinctectomy', 'thiamine', 'trophism', 'tf104pbbu', 'tasral',
#     'thyrocervical', 'tmpcvphhv', 'tmpfqv', 'strangulation',
#     'strictures', 'strain', 'emphysematous', 'spinothalamic', 'triggering',
#     'tmpf1zgqh', 'trabeculae', 'symtoms', 'sroj0fm64agheytiedya3',
#     'staphycocci', 'tpzscc8zfgle1bes8tews', 'tmpcvfodo', 'sartan',
#     'strepto', 'tmpogz1ju', 'swjygungirclqt4c', 'script', 'sotalol',
#     'tmppsxpzp', 'tibionavicular', 'tonofibril', 'tmpf7ljw4', 'tmpajvbgo',
#     'tinea', 'typhoidal', 'transformer', 'typoid', 'taussig', 'septated',
#     'tmpp51le', 'tmpla25fe', 'their', 't5wdkjqd', 'tmpnrxmxc',
#     'somatotopic', 'steps', 'tmps0zmcy', 'shatan', 'stimulating', 'suture',
#     'tyroid', 'tmpcvvwng', 'strat', 'transversion', 'trimester',
#     'tmpzb3cvx', 'tmpu5a82u', 'transjugular', 'squating', 'thermia',
#     'transabdominal', 'svn8mqpidqux3mbyrt79h', 'thiazide', 'tampered',
#     'signature', 'exhaustion', 'tubal', 'thread', 'spots', 'tmpnxoy',
#     'turnover', 'tmpbfpj1o', 'tfvha', 'stain', 'tmpaiz28m', 'tmp2x0pir',
#     'tapvr', 'transmural', 'stridor', 'terlipressin', 'existing',
#     'stylopharyngeus', 'tmp2dqm1f', 'exhibitionistic', 'tmpol9gf0', 'sheat',
#     'snailgut', 'tmpr9np9m', 'tubuloglomerular', 't96hip6omrgj4xsdvn5au',
#     'tuberosity', 'somatic', 'tmp21rezb', 'transmission', 'tabbing',
#     'tmpx5eozx', 'tmpdsleuf', 'efbcjlgkjdb03wbfs3avt', 'tmphzzil5',
#     'tamoxifnen', 'thoracolumbar', 'tygzmqzus9aa19iz1qzfl',
#     'tcfwqusfdrzsgxwnzkuza', 'tramua', 'supinator', 'tmp95p5qj',
#     'tubergenesis', 'tmpoacu2i', 'striate', 'stratum', 'stranding',
#     'subconjunctival', 'safety', 'thiabendazole', 'tmpbkc4dd', 'stimulated',
#     'tmprduw4i', 'tmp7x', 'steatohepatitis', 'tmpv5ofjl', 'stimulus',
#     'tmpyyn47c', 'sympatholytic', 'tmpijq2vp', 'subtracted',
#     'septomarginal', 'thick', 'thinking', 'tomology', 'tmpymx0gv',
#     'syncytial', 'twqjue', 'tmpaoq', 'tmppxnurc', 'triphasic', 'triceps',
#     'tbqcdfrglqhhi0y7', 'epigastric', 'tmpq8hyum', 'subthalamus',
#     'tmpl8xkpr', 'talofibular', 'taking', 'trisomy', 'spectrum',
#     'tmpsd8pl4', 'immunohistochemistry', 'tmpynshs8', 'tender', 'testis',
#     'tmpvwaz4k', 'support', 'sympathy', 'thrombomodulin', 'tojupeu',
#     'tmpx6wqph', 'snqtypmjdbia3bggdbvlz', 'tnrvm7ieybyp6l55ezu2z',
#     'tmpvzzsz2', 'supplementary', 'trigeminal', 'taenia', 'tmp3pazd5',
#     'tmpmezr8l', 'skeletel', 'tubule', 'tmpgmhxgi',
#     'pancreaticojejunostomy', 'structure', 'stylesheet', 'trapezoid',
#     'sedation', 'elastase', 'stapedial', 'tmpp0lw6h', 'tmppub', 'tmplsya6e',
#     'bacteriostatic', 'cholecystojejunostomy', 'thalami', 'tmps39lbf',
#     'tardive', 'tmpqiivzp', 'thead', 'switching', 'tmpbiorjv', 'separator',
#     'epimastigote', 'tmpy3jomr', 'trace', 'tmpkbvo2z', 'standing',
#     'subendothelium', 'stemi', 'tmpufh0no', 'sulfamethoxazole', 'timolol',
#     'tapping', 'fastigiovestibular', 'threshold', 'tmp7mjdf3', 'thigh',
#     'trswoc3gnrax1igpdca4a', 'stylohyoid', 'esophagitis', 'solution',
#     'terminale', 'tmpo1dph0', 'skeletal', 'osteoblast', 'trypanosomal',
#     'triggered', 'tmpkx5bnm', 'thickly', 'thickening', 'sterilizing',
#     'tmp6eyccg', 'tension', 'tmpbv7vyp', 'stercoralis', 'tmpcdlyx9',
#     'tmpurumfz', 'tmpuyyza0', 'thymoma', 'septal', 'subaortic', 'tenax',
#     'tmpmqjlez', 'tmpbc9knv', 'tmp68wx3h', 'tmplbrnoa',
#     'tz86ubyevab4wqiozzcep', 'salicylate', 'stimulate', 'tmpjrr9fg',
#     'subtype', 'steriod', 'tmp2rrqc6', 'severity', 'stevens', 'situation',
#     'tumors', 'ebstein', 'tmprbyfca', 'tmpexnz2x', 'tenson', 'strength',
#     'stibogluconate', 'tmps8dwhz', 'thromycin', 'tropism', 'thoracoacroial',
#     'squtptv1wqodjlku6r', 'stelectasis', 'streptomycin', 'tubulus',
#     'secreted', 'stability', 'triangle', 'tmppoc6mn', 'tmpa6bqqo', 'tzbmc',
#     'tmp0iol9d', 'tracheoesophageal', 'tmpuf0l3e', 'tmpfbr56w',
#     'sigvuenltzeyxkcdsnzjtlbqgbwf0dxjlfx0', 'interstitial', 'tmpd1zahm',
#     'tumor', 'tmpmaygjo', 'tmp16945i', 'tosufloxacin', 'streptolysin',
#     'tinidazole', 'solvent', 'supportive', 'suffocation', 'trunk',
#     'tmpedmqst', 'symptome', 'e9uslvhlndtol0', 'tmvpbrfmq9ym4', 'terminus',
#     'transfer', 'sectioned', 'tenesmus', 't4n3m0', 'tgbf6kgk', 'tmpuxep8w',
#     'tenofovir', 'staining', 'staged', 'spherocytosis', 'sympathetic',
#     'skeleton', 'intersection', 'secretin', 'stylo', 'tragedy',
#     'tachyphylaxis', 'septation', 'thresh', 'stabilization', 'tympani',
#     'tmp8bjbfq', 'start', 'trvsjrusomcuzlzuphzw', 'tmpmeb7vu', 'tamiflu',
#     'triangularis', 'teichoic', 'subarterial', 'training', 'tmpwx5dmu',
#     'tmp4kc7m', 'stromatogenic', 'elastin', 'tmpu0avha', 'torchs', 'sheath',
#     'typable', 'tylenol', 'septa', 'turica', 'trichiura', 'tmpzfzfim',
#     'sandwitch', 'tamponade', 'thyrocricoid', 'thalamus', 'thrombosis',
#     'tmpyqlxes', 'tmpc2axc9', 'stent', 'subcutaneous', 'tibial',
#     'tcekdkhk69dn', 'tangle', 'tuberculous', 'storing', 'tmpurowik', 'toxic'
# ]

# wordset = preprocessList(wordset)

# print(len(wordset))
# start = time.time()
# print(fuzzymatchBatch(preprocess('test'), wordset))
# print(time.time() - start)
# print(1)
